config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  # get 'users/new'

  # get 'user/name:string'

  # get 'user/email:string'

  # get 'sessions/new'

  root 'current_pages#home'
  #NEED TO to or else heroku has not idea what to do 	

  get '/aboutus', to: 'current_pages#aboutus'
  get '/ourwork', to: 'current_pages#ourwork'
  get '/properties', to: 'current_pages#properties'
  get '/donations', to: 'current_pages#donations'
  get '/accepteddonations', to: 'current_pages#accepteddonations'
  get '/testimonials', to: 'current_pages#testimonials'
  get '/contactus', to: 'current_pages#contactus'
  #Falls under a different constructor (Since we are also calling a model on it)
  get '/signup', to: 'users#new'
  
  resources :users #Implements all RESTful resources for users model


  #Sessions isn't part of a model like users 
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new,:create,:edit,:update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<h5 class="cent_text no_pad">Created by Pranav Sriram | The Cheng Foundation Copyright 2017: <a href="http://apperun.com/">Apperun Technologies</a></h5>
	</div> 
</footer>

app/views/layouts/_header.html.erb
<header>
      <div class = "container">
        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Overall NavBar set up stuff below  -->   
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!--Navbar heading for the foundtion -->
              <a class="navbar-brand" href="/">
                <img class= "title" src="/images/Title.png" alt="Cheng Foundation"> 
              </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <!-- Left aligned links -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About Us", aboutus_path %></li>
                <li><%= link_to "Our Work", ourwork_path %></li>
                <li><%= link_to "Properties", properties_path %></li>
                <li><%= link_to "Donations", donations_path %></li>
                <li><%= link_to "Accepted Donations", accepteddonations_path%></li>
                <li><%= link_to "Testimonials", testimonials_path %></li>
              </ul>
              <!-- Right aligned links -->
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a class="btn btn-social-icon btn-facebook btn-lg" href="https://www.facebook.com/bryce.cheng.1" target="_blank">
                  <span class="fa fa-facebook"></span>
                </a>
              </li>
              <li>
                  <a class="btn btn-social-icon btn-twitter btn-lg" href="https://twitter.com/bryce_cheng" target="_blank">
                  <span class="fa fa-twitter"></span>
                </a>
              </li>
              <li>
                  <a class="btn btn-social-icon btn-instagram btn-lg" href="https://www.instagram.com/b_ryce_cheng/" target="_blank">
                  <span class="fa fa-instagram"></span>
                </a>
              </li>
              <li>
                  <a class="btn btn-social-icon btn-google btn-lg" href="https://plus.google.com/111061049653291785131" target="_blank">
                  <span class="fa fa-google"></span>
                </a>
              </li>
                <li><%= link_to "Contact Us", contactus_path %></li>
                <% if logged_in? %>                   
                        <li><%= link_to "Members", users_path %></li>
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: :delete %>
                    </li> 
                  <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                  <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>-->
	<%= favicon_link_tag 'favicon.ico' %>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato|PT+Serif" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
	<script src="https://use.fontawesome.com/ebaf6b7b9f.js"></script>
  	<%= render 'layouts/shim' %>
  </head>
  <body>
  	  <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> cent_text" ><strong>A ROYAL CHENG NOTIFICATION</strong></div>
        <div class="alert alert-<%= message_type %> cent_text"><strong><%= message %></strong></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-101931366-2', 'auto');
    ga('send', 'pageview');
</script>
</html>